# Generated by Django 4.0.5 on 2022-06-21 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomtype_code', models.CharField(max_length=5, unique=True, verbose_name='Room Type Code')),
                ('roomtype_name', models.CharField(max_length=50, verbose_name='Room Type Name')),
                ('roomtype_number', models.PositiveIntegerField(verbose_name='Total Number of Rooms')),
                ('roomtype_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Rate')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('roomtype_extrainfo', models.TextField(blank=True, null=True, verbose_name='Extra Information')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'ordering': ['is_active', 'roomtype_rate'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(default='-', max_length=50, verbose_name='Room Number')),
                ('room_status', models.CharField(choices=[('cv', 'Clean Vacant'), ('co', 'Clean Occupied'), ('dv', 'Dirty Vacant'), ('do', 'Dirty Occupied')], default='dv', max_length=50, verbose_name='Status of Room')),
                ('room_dimension', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Room Area')),
                ('room_totalbeds', models.PositiveIntegerField(default=1, verbose_name='Number of Beds')),
                ('room_totalbaths', models.PositiveIntegerField(default=1, verbose_name='Number of Baths')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_occupied', models.BooleanField(default=False, verbose_name='Is Occupied')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('room_type', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype', verbose_name='Room Type')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_number'],
            },
        ),
    ]
