# Generated by Django 4.0.5 on 2022-06-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(editable=False, max_length=50, verbose_name='Room Number'),
        ),
    ]
