# Generated by Django 4.0.5 on 2022-06-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_options_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['is_active', 'roomtype_rate'], 'verbose_name': 'Room Type', 'verbose_name_plural': 'Room Types'},
        ),
    ]
