# Generated by Django 4.0.5 on 2022-06-21 12:02

import clients.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(default=clients.models.clientNumberGenerator, max_length=50, verbose_name='Client Number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(default=' ', max_length=50, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1, verbose_name='Gender')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('address', models.TextField(verbose_name='Residential Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actiive')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='FundingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Funding Code')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone', models.CharField(default='-', max_length=13, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('country', models.CharField(default='-', max_length=120, verbose_name='Country')),
                ('region', models.CharField(default='-', max_length=50, verbose_name='Region')),
                ('town', models.CharField(default='-', max_length=50, verbose_name='Town/City')),
                ('street', models.CharField(default='-', max_length=50, verbose_name='Street')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Funding Account',
                'verbose_name_plural': 'Funding Accounts',
            },
        ),
        migrations.CreateModel(
            name='ClientFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Validity From')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Validity To')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Discount')),
                ('payment_type', models.CharField(choices=[('', '-----------------'), ('credit', 'Credit'), ('cash', 'Cash')], max_length=10, verbose_name='Payment Type')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client')),
                ('fundingaccount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.fundingaccount', verbose_name='Funding Account')),
            ],
            options={
                'verbose_name': 'Client Funding',
                'verbose_name_plural': 'Client Fundings',
                'ordering': ('client',),
            },
        ),
        migrations.AddField(
            model_name='client',
            name='funding_account',
            field=models.ManyToManyField(through='clients.ClientFunding', to='clients.fundingaccount', verbose_name='Funding Accounts'),
        ),
    ]
