# Generated by Django 4.0.5 on 2022-06-19 11:14

import clients.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Validity From')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Validity To')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Benefit',
                'verbose_name_plural': 'Benefits',
            },
        ),
        migrations.CreateModel(
            name='FundingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('phone', models.CharField(default='-', max_length=13, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('country', models.CharField(default='-', max_length=120, verbose_name='Country')),
                ('region', models.CharField(default='-', max_length=50, verbose_name='Region')),
                ('town', models.CharField(default='-', max_length=50, verbose_name='Town/City')),
                ('street', models.CharField(default='-', max_length=50, verbose_name='Street')),
            ],
            options={
                'verbose_name': 'FundingAccount',
                'verbose_name_plural': 'FundingAccounts',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_number', models.CharField(default=clients.models.clientNumberGenerator, max_length=50, verbose_name='Client Number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=1, verbose_name='Gender')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Age')),
                ('address', models.TextField(verbose_name='Residential Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actiive')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('funding_account', models.ManyToManyField(through='clients.Benefit', to='clients.fundingaccount', verbose_name='Funding Accounts')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.AddField(
            model_name='benefit',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='fundingaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.fundingaccount', verbose_name='Funding Account'),
        ),
    ]
