# Generated by Django 4.0.5 on 2022-07-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='middle_name',
            field=models.CharField(default='-', max_length=50, verbose_name='Middle Name'),
        ),
    ]
