# Generated by Django 4.0.5 on 2022-06-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingaccount',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Funding Code'),
        ),
    ]
