# Generated by Django 4.0.5 on 2022-06-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_fundingaccount_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingaccount',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount'),
        ),
    ]
