# Generated by Django 4.0.5 on 2022-06-19 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_fundingaccount_discount_alter_benefit_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Validity From')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Validity To')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('discount', models.PositiveIntegerField(default=0, verbose_name='Discount')),
                ('payment_type', models.CharField(max_length=10, verbose_name='Payment Type')),
            ],
            options={
                'verbose_name': 'Client Funding',
                'verbose_name_plural': 'Client Fundings',
            },
        ),
        migrations.AlterModelOptions(
            name='fundingaccount',
            options={'verbose_name': 'Funding Account', 'verbose_name_plural': 'Funding Accounts'},
        ),
        migrations.AlterField(
            model_name='client',
            name='funding_account',
            field=models.ManyToManyField(through='clients.ClientFunding', to='clients.fundingaccount', verbose_name='Funding Accounts'),
        ),
        migrations.DeleteModel(
            name='Benefit',
        ),
        migrations.AddField(
            model_name='clientfunding',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='clientfunding',
            name='fundingaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.fundingaccount', verbose_name='Funding Account'),
        ),
    ]
