# Generated by Django 4.0.5 on 2022-06-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_clientfunding_alter_fundingaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfunding',
            name='payment_type',
            field=models.CharField(choices=[('', '-----------------'), ('credit', 'Credit'), ('cash', 'Cash')], max_length=10, verbose_name='Payment Type'),
        ),
    ]
