# Generated by Django 4.0.5 on 2022-06-20 12:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import field_validations
import reservations.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(default=reservations.models.generateBookingNumber, max_length=50, verbose_name='Booking Number')),
                ('booking_from', models.DateTimeField(default=django.utils.timezone.now, validators=[field_validations.validate_bookingfrom], verbose_name='Booking From')),
                ('booking_to', models.DateTimeField(verbose_name='Booking To')),
                ('booking_roomnumber', models.PositiveIntegerField(default=1, verbose_name='Number of Rooms')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('booking_status', models.CharField(default='unattended', max_length=20, verbose_name='Status')),
                ('booking_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Booking By')),
                ('booking_roomtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype', verbose_name='Room Type')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Check-in At')),
                ('checkin_type', models.CharField(choices=[('hd', 'Half Day'), ('re', 'Regular Check-in')], default='re', max_length=4, verbose_name='Check-in Type')),
                ('early_checkin', models.BooleanField(default=False, verbose_name='Early Check-in')),
                ('checkin_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reservations.booking', verbose_name='Booking')),
                ('funding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.clientfunding', verbose_name='Funding Account')),
                ('rooms', models.ManyToManyField(to='rooms.room', verbose_name='Rooms')),
            ],
            options={
                'verbose_name': 'Check In',
                'verbose_name_plural': 'Check Ins',
            },
        ),
    ]
