# Generated by Django 4.0.5 on 2022-06-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_roomtype_roomtype_code'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='rooms',
        ),
        migrations.AddField(
            model_name='checkin',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room', verbose_name='Rooms'),
        ),
    ]
